"""create_ai_agent_sessions_table

Revision ID: 140d1dc584c8
Revises: 
Create Date: 2026-05-17 12:12:38.526645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140d1dc584c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_agent_sessions_tenant_id'), 'ai_agent_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_agent_sessions_user_id'), 'ai_agent_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_agent_sessions_user_id'), table_name='ai_agent_sessions')
    op.drop_index(op.f('ix_ai_agent_sessions_tenant_id'), table_name='ai_agent_sessions')
    op.drop_table('ai_agent_sessions')
    # ### end Alembic commands ###
