import type { CollectionConfig } from 'payload'
import { getTenantIds } from '../Users/utils'

/**
 * AIPromptHistory collection.
 * Logs all natural language prompts used and the corresponding generation outcomes.
 * Enforces tenant isolation.
 *
 * T007b - Initialize prompt logging collection configuration for AIPromptHistory
 */
export const AIPromptHistory: CollectionConfig = {
  slug: 'ai-prompt-history',
  admin: {
    useAsTitle: 'prompt',
    description: 'Logs of all natural language prompts and generated schemas.',
    group: 'AI Architect',
    defaultColumns: ['prompt', 'user', 'createdAt'],
  },
  access: {
    read: ({ req: { user } }) => {
      if (!user) return false
      if ((user as any).role === 'super-admin') return true
      const tenantIds = getTenantIds(user)
      if (tenantIds.length === 0) return false
      return {
        tenant: {
          in: tenantIds,
        },
      }
    },
    create: ({ req: { user } }) =>
      Boolean(user) &&
      ((user as any).role === 'super-admin' ||
        (user as any).role === 'tenant-admin' ||
        (user as any).role === 'editor'),
    update: () => false,
    delete: () => false,
  },
  fields: [
    {
      name: 'prompt',
      type: 'textarea',
      required: true,
      label: 'Prompt',
      admin: {
        description: 'The natural language prompt entered by the user.',
      },
    },
    {
      name: 'generatedSchema',
      type: 'json',
      required: true,
      label: 'Generated Schema',
      admin: {
        description: 'The schema generated by the AI model in response.',
      },
    },
    {
      name: 'user',
      type: 'relationship',
      relationTo: 'users',
      required: true,
      label: 'User',
      defaultValue: ({ req }) => req.user?.id,
      admin: {
        description: 'The user who initiated the prompt.',
      },
    },
  ],
  timestamps: true,
}
