import type { CollectionConfig } from 'payload'
import { generateSchemaEndpoint, getSessionStatusEndpoint, exportSchemaEndpoint, exportSchemaTSEndpoint } from './endpoints'
import { getTenantIds } from '../Users/utils'
import { beforeChangeHook } from './hooks'

const slugify = (text: string): string => {
  return text
    .toString()
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^\w\-]+/g, '')
    .replace(/\-\-+/g, '-')
}

/**
 * ContentTypes collection.
 * Stores JSON schemas for content types that are either hand-crafted by
 * editors or dynamically generated by the AI Agent (T015 / T017).
 *
 * Each ContentType belongs to a tenant and defines the structure that
 * ContentItems of this type must conform to.
 *
 * T015 - Implement Payload ContentType dynamic schema logic
 */
export const ContentTypes: CollectionConfig = {
  slug: 'content-types',
  admin: {
    useAsTitle: 'name',
    description: 'Dynamic content schemas, possibly AI-generated.',
    components: {
      views: {
        edit: {
          default: {
            Component: '/src/components/views/ContentTypes/GeneratorView#GeneratorView',
          },
        },
      },
    },
  },
  access: {
    read: ({ req: { user } }) => {
      if (!user) return false
      if ((user as any).role === 'super-admin') return true
      const tenantIds = getTenantIds(user)
      if (tenantIds.length === 0) return false
      return {
        tenant: {
          in: tenantIds,
        },
      }
    },
    create: ({ req: { user } }) =>
      Boolean(user) &&
      ((user as any).role === 'super-admin' ||
        (user as any).role === 'tenant-admin' ||
        (user as any).role === 'editor'),
    update: ({ req: { user } }) => {
      if (!user) return false
      if ((user as any).role === 'super-admin') return true
      const tenantIds = getTenantIds(user)
      if (tenantIds.length === 0) return false
      return {
        tenant: {
          in: tenantIds,
        },
      }
    },
    delete: ({ req: { user } }) => {
      if (!user) return false
      if ((user as any).role === 'super-admin') return true
      const tenantIds = getTenantIds(user)
      if (tenantIds.length === 0) return false
      return {
        tenant: {
          in: tenantIds,
        },
      }
    },
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
      label: 'Name',
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      label: 'Slug',
      defaultValue: '',
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      options: [
        { label: 'Draft', value: 'draft' },
        { label: 'Published', value: 'published' },
      ],
      defaultValue: 'draft',
      label: 'Status',
    },
    {
      name: 'originalSchema',
      type: 'json',
      required: false,
      label: 'Original JSON Schema',
      admin: {
        description: 'The originally suggested AI schema before any visual refinement.',
      },
    },

    {
      name: 'schema',
      type: 'json',
      required: true,
      label: 'JSON Schema',
      admin: {
        description:
          'The JSON schema defining the structure of this content type. ' +
          'May be generated by the AI Agent via POST /api/ai/generate-schema.',
      },
    },
    {
      name: 'generatedByAI',
      type: 'checkbox',
      defaultValue: false,
      label: 'Generated by AI',
      admin: {
        description: 'Flag indicating this schema was created via the AI Agent.',
      },
    },
    {
      name: 'aiSessionId',
      type: 'text',
      label: 'AI Session ID',
      admin: {
        description:
          'Reference to the AIAgentSession in the AI Microservice that generated this schema.',
        condition: (data) => Boolean(data?.generatedByAI),
      },
    },
  ],
  hooks: {
    beforeValidate: [
      ({ data }) => {
        if (data && !data.slug && data.name) {
          data.slug = slugify(data.name)
        }
        return data
      },
    ],
    beforeChange: [beforeChangeHook],
  },
  // T017: Custom AI endpoint for schema generation
  endpoints: [generateSchemaEndpoint, getSessionStatusEndpoint, exportSchemaEndpoint, exportSchemaTSEndpoint],
  timestamps: true,
}
