import type { CollectionConfig } from 'payload'
import { generateSchemaEndpoint } from './endpoints.js'

/**
 * ContentTypes collection.
 * Stores JSON schemas for content types that are either hand-crafted by
 * editors or dynamically generated by the AI Agent (T015 / T017).
 *
 * Each ContentType belongs to a tenant and defines the structure that
 * ContentItems of this type must conform to.
 *
 * T015 - Implement Payload ContentType dynamic schema logic
 */
export const ContentTypes: CollectionConfig = {
  slug: 'content-types',
  admin: {
    useAsTitle: 'name',
    description: 'Dynamic content schemas, possibly AI-generated.',
  },
  access: {
    read: ({ req: { user } }) => {
      if (!user) {
        // Allow public read for API-key authenticated delivery
        return true
      }
      if (user.role === 'super-admin') return true
      return {
        tenantId: {
          equals: user.tenantId,
        },
      }
    },
    create: ({ req: { user } }) =>
      Boolean(user) &&
      (user?.role === 'super-admin' ||
        user?.role === 'tenant-admin' ||
        user?.role === 'editor'),
    update: ({ req: { user } }) => {
      if (!user) return false
      if (user.role === 'super-admin') return true
      return {
        tenantId: {
          equals: user.tenantId,
        },
      }
    },
    delete: ({ req: { user } }) =>
      user?.role === 'super-admin' || user?.role === 'tenant-admin',
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
      label: 'Name',
    },
    {
      name: 'tenantId',
      type: 'relationship',
      relationTo: 'tenants',
      required: true,
      label: 'Tenant',
      admin: {
        description: 'The tenant that owns this content type.',
      },
    },
    {
      name: 'schema',
      type: 'json',
      required: true,
      label: 'JSON Schema',
      admin: {
        description:
          'The JSON schema defining the structure of this content type. ' +
          'May be generated by the AI Agent via POST /api/ai/generate-schema.',
      },
    },
    {
      name: 'generatedByAI',
      type: 'checkbox',
      defaultValue: false,
      label: 'Generated by AI',
      admin: {
        description: 'Flag indicating this schema was created via the AI Agent.',
      },
    },
    {
      name: 'aiSessionId',
      type: 'text',
      label: 'AI Session ID',
      admin: {
        description:
          'Reference to the AIAgentSession in the AI Microservice that generated this schema.',
        condition: (data) => Boolean(data?.generatedByAI),
      },
    },
  ],
  // T017: Custom AI endpoint for schema generation
  endpoints: [generateSchemaEndpoint],
  timestamps: true,
}
