import type { CollectionConfig, Where } from 'payload'
import { generateSchemaEndpoint, getSessionStatusEndpoint, postSessionMessageEndpoint, exportSchemaEndpoint, exportSchemaTSEndpoint, listCollectionsEndpoint } from './endpoints'
import { getTenantIds } from '../Users/utils'
import { beforeChangeHook, afterChangeHook } from './hooks'

const slugify = (text: string): string => {
  return text
    .toString()
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^\w\-]+/g, '')
    .replace(/\-\-+/g, '-')
}

/**
 * ContentTypes collection.
 * Stores JSON schemas for content types that are either hand-crafted by
 * editors or dynamically generated by the AI Agent (T015 / T017).
 *
 * Each ContentType belongs to a tenant and defines the structure that
 * ContentItems of this type must conform to.
 *
 * T015 - Implement Payload ContentType dynamic schema logic
 */
export const ContentTypes: CollectionConfig = {
  slug: 'content-types',
  labels: {
    singular: 'Content Type',
    plural: 'Content Types',
  },
  admin: {
    useAsTitle: 'name',
    description: 'Dynamic content schemas, possibly AI-generated.',
    components: {
      views: {
        list: {
          Component: '/src/components/views/ContentTypeListPage#ContentTypeListPage',
        },
        edit: {
          default: {
            Component: '/src/components/views/ContentTypes/GeneratorView#GeneratorView',
          },
        },
      },
    },
  },
  access: {
    read: () => true,
    admin: () => true,
    create: ({ req: { user } }) => {
      console.log('--- CONTENT-TYPES CREATE ACCESS ---')
      console.log('User:', JSON.stringify(user))
      return (
        Boolean(user) &&
        ((user as any).role === 'super-admin' ||
          (user as any).role === 'tenant-admin' ||
          (user as any).role === 'editor')
      )
    },
    update: ({ req: { user } }) => {
      if (!user) return false
      if ((user as any).role === 'super-admin') return true
      const tenantIds = getTenantIds(user)
      if (tenantIds.length === 0) return false
      return {
        and: [
          {
            tenant: {
              in: tenantIds,
            },
          },
          {
            isGlobal: {
              not_equals: true,
            },
          },
        ],
      } as unknown as Where
    },
    delete: ({ req: { user } }) => {
      if (!user) return false
      if ((user as any).role === 'super-admin') return true
      const tenantIds = getTenantIds(user)
      if (tenantIds.length === 0) return false
      return {
        and: [
          {
            tenant: {
              in: tenantIds,
            },
          },
          {
            isGlobal: {
              not_equals: true,
            },
          },
        ],
      } as unknown as Where
    },
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
      label: 'Name',
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      label: 'Slug',
      defaultValue: '',
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      options: [
        { label: 'Draft', value: 'draft' },
        { label: 'Published', value: 'published' },
      ],
      defaultValue: 'draft',
      label: 'Status',
    },
    {
      name: 'originalSchema',
      type: 'json',
      required: false,
      label: 'Original JSON Schema',
      admin: {
        description: 'The originally suggested AI schema before any visual refinement.',
      },
    },

    {
      name: 'schema',
      type: 'json',
      required: true,
      label: 'JSON Schema',
      admin: {
        description:
          'The JSON schema defining the structure of this content type. ' +
          'May be generated by the AI Agent via POST /api/ai/generate-schema.',
      },
    },
    {
      name: 'generatedByAI',
      type: 'checkbox',
      defaultValue: false,
      label: 'Generated by AI',
      admin: {
        description: 'Flag indicating this schema was created via the AI Agent.',
      },
    },
    {
      name: 'aiSessionId',
      type: 'text',
      label: 'AI Session ID',
      admin: {
        description:
          'Reference to the AIAgentSession in the AI Microservice that generated this schema.',
        condition: (data) => Boolean(data?.generatedByAI),
      },
    },
    {
      name: 'version',
      type: 'number',
      required: true,
      defaultValue: 1,
      admin: {
        hidden: true,
      },
    },
    {
      name: 'isGlobal',
      type: 'checkbox',
      label: 'Global Content Type',
      defaultValue: false,
      admin: {
        position: 'sidebar',
        description: 'Available to all tenants by default. Only Super Admins can manage global content types.',
      },
      access: {
        update: ({ req: { user } }) => (user as any)?.role === 'super-admin',
        create: ({ req: { user } }) => (user as any)?.role === 'super-admin',
      },
    },
    {
      name: 'tenant',
      type: 'relationship',
      relationTo: 'tenants',
      required: false,
      index: true,
      admin: {
        position: 'sidebar',
      },
      validate: (val: any, { data }: any) => {
        if (data?.isGlobal) return true
        if (!val) return 'Tenant is required for non-global content types'
        return true
      },
    },
  ],
  hooks: {
    beforeValidate: [
      ({ data }) => {
        if (data && !data.slug && data.name) {
          data.slug = slugify(data.name)
        }
        return data
      },
    ],
    beforeChange: [beforeChangeHook],
    afterChange: [afterChangeHook],
  },
  // T017: Custom AI endpoint for schema generation
  endpoints: [
    generateSchemaEndpoint,
    getSessionStatusEndpoint,
    postSessionMessageEndpoint,
    exportSchemaEndpoint,
    exportSchemaTSEndpoint,
    listCollectionsEndpoint,
  ],
  timestamps: true,
}
