"""
FastAPI AI Microservice entry point.

Exposes:
  - POST /api/ai/generate-schema   – AI schema generation (T017 integration)
  - GET  /api/ai/sessions/{id}     – Session status polling
  - POST /api/ai/copilot/edit      – AI copilot section edit (T023)
  - GET  /health                   – Health check

T003 - Initialize FastAPI Microservice project
"""

from __future__ import annotations

from contextlib import asynccontextmanager
from uuid import UUID

from fastapi import FastAPI, HTTPException, Request, Security, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import APIKeyHeader
from pydantic import BaseModel, field_validator

from src.application.ai_service import AIService
from src.infrastructure.config import settings

# ── Security ──────────────────────────────────────────────────────────────────

INTERNAL_SECRET = settings.INTERNAL_SERVICE_SECRET
_api_key_header = APIKeyHeader(name="X-Internal-Secret", auto_error=False)


def _require_internal_secret(key: str | None = Security(_api_key_header)) -> None:
    """Validate the internal service-to-service secret header."""
    if not INTERNAL_SECRET:
        # If no secret is configured, allow all (development mode)
        return
    if key != INTERNAL_SECRET:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid internal service secret.",
        )


# ── Lifespan ──────────────────────────────────────────────────────────────────


@asynccontextmanager
async def lifespan(app: FastAPI):  # noqa: ANN001
    """Application lifespan – initialise / teardown shared resources."""
    app.state.ai_service = AIService()
    yield
    # Teardown (DB connections, etc.) goes here.


# ── App ───────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Hermes AI Agent Service",
    description=(
        "Conversational AI microservice for schema generation and content copilot. "
        "Part of the Hermes AI platform."
    ),
    version="0.1.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS.split(","),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Request / Response models ─────────────────────────────────────────────────


class GenerateSchemaRequest(BaseModel):
    """Payload for POST /api/ai/generate-schema."""

    prompt: str
    tenant_id: UUID
    user_id: UUID

    @field_validator("prompt")
    @classmethod
    def prompt_must_not_be_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("prompt must not be empty.")
        return v.strip()


class GenerateSchemaResponse(BaseModel):
    """Response for POST /api/ai/generate-schema."""

    session_id: str
    content_schema: dict  # renamed from 'schema' to avoid BaseModel shadow
    status: str


class CopilotEditRequest(BaseModel):
    """Payload for POST /api/ai/copilot/edit."""

    content_item_id: str
    section_id: str
    prompt: str
    tenant_id: UUID
    user_id: UUID


# ── Routes ────────────────────────────────────────────────────────────────────


@app.get("/health", tags=["Meta"])
async def health() -> dict:
    """Health check endpoint."""
    return {"status": "ok", "service": "ai-agent-service"}


@app.post(
    "/api/ai/generate-schema",
    response_model=GenerateSchemaResponse,
    status_code=status.HTTP_200_OK,
    tags=["AI"],
    summary="Generate a content schema from natural language",
    dependencies=[Security(_require_internal_secret)],
)
async def generate_schema(
    body: GenerateSchemaRequest,
    request: Request,
) -> GenerateSchemaResponse:
    """
    Accepts a natural-language prompt and returns a structured content schema
    generated by the LLM.  Creates an AIAgentSession to track the conversation.

    T016 - Invokes AIService.generate_schema
    T018 - Called by the CMS generate-schema endpoint
    """
    ai_service: AIService = request.app.state.ai_service
    try:
        result = await ai_service.generate_schema(
            prompt=body.prompt,
            tenant_id=body.tenant_id,
            user_id=body.user_id,
        )
        return GenerateSchemaResponse(
            session_id=result["sessionId"],
            content_schema=result["schema"],
            status=result["status"],
        )
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    except RuntimeError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        ) from exc


@app.get(
    "/api/ai/sessions/{session_id}",
    tags=["AI"],
    summary="Get AI session status",
    dependencies=[Security(_require_internal_secret)],
)
async def get_session(session_id: str, request: Request) -> dict:
    """Return the current status and context of an AIAgentSession."""
    ai_service: AIService = request.app.state.ai_service
    session = ai_service.get_session(session_id)
    if session is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Session '{session_id}' not found.",
        )
    return {
        "id": str(session.id),
        "status": session.status,
        "tenant_id": str(session.tenant_id),
        "user_id": str(session.user_id),
        "message_count": len(session.context),
        "created_at": session.created_at.isoformat(),
        "updated_at": session.updated_at.isoformat(),
    }


@app.post(
    "/api/ai/copilot/edit",
    tags=["AI"],
    summary="Apply an AI edit to a specific content section",
    dependencies=[Security(_require_internal_secret)],
)
async def copilot_edit(body: CopilotEditRequest, request: Request) -> dict:
    """
    Applies the AI copilot's suggestion to a specific section of content.
    Returns the edited content section text.

    T023 - Implement AI service logic for localized section editing
    """
    from src.application.copilot_service import CopilotService  # noqa: PLC0415

    copilot_service = CopilotService(request.app.state.ai_service)
    try:
        edited_content = await copilot_service.edit_section(
            content_item_id=body.content_item_id,
            section_id=body.section_id,
            prompt=body.prompt,
            tenant_id=body.tenant_id,
            user_id=body.user_id,
        )
        return {"section_id": body.section_id, "content": edited_content}
    except RuntimeError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        ) from exc
