"""
Domain-level Pydantic structures for schema model output.
"""

from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class FieldDefinition(BaseModel):
    """
    Structured model for individual fields inside a content type schema.
    """
    name: str = Field(
        description="Alphanumeric key/slug representing the field variable"
    )
    type: Literal[
        "text", "number", "boolean", "date", "richText", "json",
        "relationship", "select", "upload", "array", "blocks"
    ] = Field(
        description="Payload CMS supported field type"
    )
    required: bool = Field(
        description="Flag indicating if the field is mandatory",
        default=False
    )
    label: str = Field(
        description="User friendly interface title label"
    )
    description: Optional[str] = Field(
        description="Explanation or guidance for authors",
        default=None
    )
    localized: Optional[bool] = Field(
        description="Multi-locale translations enabled flag",
        default=False
    )
    unique: Optional[bool] = Field(
        description="Unique indexing constraint",
        default=False
    )
    fields: Optional[List["FieldDefinition"]] = Field(
        description="Nested subfields (only applicable if type is 'array')",
        default=None
    )
    blocks: Optional[List[Dict[str, Any]]] = Field(
        description="Nested block configurations (only applicable if type is 'blocks')",
        default=None
    )


# Standard recursive rebuilding for Pydantic v2
FieldDefinition.model_rebuild()


class ContentSchemaOutput(BaseModel):
    """
    The final structured schema generated by the AI model.
    """
    name: str = Field(
        description="The display name of the content schema/type"
    )
    fields: List[FieldDefinition] = Field(
        description="List of fields comprising the schema structure"
    )
    explanation: Optional[str] = Field(
        description="Helpful summary or description of the schema modeling rationale",
        default=None
    )
