import type { CollectionConfig } from 'payload'

/**
 * Generate a beautifully formatted Payload CMS 3.x static CollectionConfig TypeScript file.
 */
export function generatePayloadTS(name: string, slug: string, fields: any[]): string {
  const normalizedClassName = name
    .replace(/[^a-zA-Z0-9]/g, '')
    .replace(/^[0-9]/, 'CT_$&') || 'GeneratedCollection'

  const tsFields = fields.map(f => {
    const lines = [
      `    {`,
      `      name: '${f.name}',`,
      `      type: '${f.type}',`,
    ]

    if (f.label) {
      lines.push(`      label: '${f.label}',`)
    }
    if (f.required) {
      lines.push(`      required: true,`)
    }
    if (f.unique) {
      lines.push(`      unique: true,`)
    }
    if (f.defaultValue !== undefined && f.defaultValue !== null && f.defaultValue !== '') {
      const dv = typeof f.defaultValue === 'string' ? `'${f.defaultValue}'` : f.defaultValue
      lines.push(`      defaultValue: ${dv},`)
    }
    if (f.type === 'select' && Array.isArray(f.options)) {
      lines.push(`      options: [`)
      const seenValues = new Set<string>()
      f.options.forEach((opt: string) => {
        const val = opt.toLowerCase().replace(/[^a-z0-9_-]/g, '')
        if (!seenValues.has(val)) {
          seenValues.add(val)
          lines.push(`        { label: '${opt}', value: '${val}' },`)
        }
      })
      lines.push(`      ],`)
    }
    if (f.type === 'relationship' && f.relationTo) {
      lines.push(`      relationTo: '${f.relationTo}',`)
    }
    if (f.description) {
      lines.push(`      admin: {`)
      lines.push(`        description: '${f.description.replace(/'/g, "\\'")}',`)
      lines.push(`      },`)
    }

    lines.push(`    }`)
    return lines.join('\n')
  }).join(',\n')

  return `import type { CollectionConfig } from 'payload'

/**
 * Static CollectionConfig for "${name}".
 * Auto-generated by Hermes AI Content Architect.
 */
export const ${normalizedClassName}: CollectionConfig = {
  slug: '${slug}',
  admin: {
    useAsTitle: 'title',
    description: 'Static definition exported from dynamic Hermes AI content schema.',
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
    },
    {
      name: 'fieldsData',
      type: 'group',
      label: 'Fields Data',
      fields: [
${tsFields}
      ]
    }
  ]
}
`
}
