/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'api-keys': ApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    'content-types': ContentType;
    'content-items': ContentItem;
    'hosted-sites': HostedSite;
    media: Media;
    'audit-logs': AuditLog;
    'api-keys': ApiKey;
    'ai-prompt-history': AiPromptHistory;
    'drafting-sessions': DraftingSession;
    'style-modifiers': StyleModifier;
    'ai-audit-logs': AiAuditLog;
    'ai-rate-limits': AiRateLimit;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'content-types': ContentTypesSelect<false> | ContentTypesSelect<true>;
    'content-items': ContentItemsSelect<false> | ContentItemsSelect<true>;
    'hosted-sites': HostedSitesSelect<false> | HostedSitesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    'ai-prompt-history': AiPromptHistorySelect<false> | AiPromptHistorySelect<true>;
    'drafting-sessions': DraftingSessionsSelect<false> | DraftingSessionsSelect<true>;
    'style-modifiers': StyleModifiersSelect<false> | StyleModifiersSelect<true>;
    'ai-audit-logs': AiAuditLogsSelect<false> | AiAuditLogsSelect<true>;
    'ai-rate-limits': AiRateLimitsSelect<false> | AiRateLimitsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | ApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Organizations or workspaces using the CMS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Unique URL-safe identifier for the tenant.
   */
  slug: string;
  status: 'active' | 'suspended' | 'archived';
  tier: 'standard' | 'premium' | 'enterprise';
  defaultLocale: 'en' | 'es' | 'fr' | 'de';
  defaultLLMModel?: ('openai/gpt-4o' | 'anthropic/claude-3-5-sonnet' | 'google/gemini-2.5-flash') | null;
  defaultImageModel?: 'openai/dall-e-3' | null;
  /**
   * Hostnames mapped to this tenant for branded access.
   */
  domains: {
    hostname: string;
    isPrimary?: boolean | null;
    id?: string | null;
  }[];
  branding?: {
    logo?: (number | null) | Media;
    primaryColor?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Reference to the tenant this media belongs to.
   */
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * CMS users managed via multi-tenant architecture.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'super-admin' | 'tenant-admin' | 'editor';
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Dynamic content schemas, possibly AI-generated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-types".
 */
export interface ContentType {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  status: 'draft' | 'published';
  /**
   * The originally suggested AI schema before any visual refinement.
   */
  originalSchema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The JSON schema defining the structure of this content type. May be generated by the AI Agent via POST /api/ai/generate-schema.
   */
  schema:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Flag indicating this schema was created via the AI Agent.
   */
  generatedByAI?: boolean | null;
  /**
   * Reference to the AIAgentSession in the AI Microservice that generated this schema.
   */
  aiSessionId?: string | null;
  version: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Content entries per tenant and content type.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-items".
 */
export interface ContentItem {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  contentType: number | ContentType;
  /**
   * Structured JSON data holding actual field values matching the selected Content Type schema.
   */
  fieldsData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Rich text / block-based content. Supports lexical editor blocks.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Managed deployments of front-end templates for your tenant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hosted-sites".
 */
export interface HostedSite {
  id: number;
  name: string;
  template: 'nextjs-blog' | 'astro-portfolio';
  /**
   * Optional custom domain for this site.
   */
  domain?: string | null;
  status?: ('pending' | 'deploying' | 'active' | 'failed') | null;
  deployedUrl?: string | null;
  tenant: number | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Security and operational event logs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  /**
   * E.g., tenant_resolution_failure, impersonation_start
   */
  action: string;
  severity: 'info' | 'warning' | 'error';
  /**
   * Reference to the tenant this log belongs to.
   */
  tenant?: (number | null) | Tenant;
  /**
   * The user who performed the action.
   */
  user?: (number | null) | User;
  /**
   * Extra context (IP, hostname, etc.).
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * True if action was performed via impersonation.
   */
  isImpersonated?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys for programmatic content delivery access.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * A human-readable name for this API key.
   */
  label: string;
  /**
   * Identifier email address associated with this API key.
   */
  email: string;
  /**
   * Optional expiry date. Leave empty for no expiry.
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'api-keys';
}
/**
 * Logs of all natural language prompts and generated schemas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-prompt-history".
 */
export interface AiPromptHistory {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * The natural language prompt entered by the user.
   */
  prompt: string;
  /**
   * The schema generated by the AI model in response.
   */
  generatedSchema:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The user who initiated the prompt.
   */
  user: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drafting-sessions".
 */
export interface DraftingSession {
  id: number;
  tenant?: (number | null) | Tenant;
  user: number | User;
  contentType: number | ContentType;
  status: 'active' | 'expired';
  draftData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  mainMedia?: (number | null) | Media;
  activeLocale: string;
  selectedModel?: string | null;
  lastActivityAt: string;
  versions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "style-modifiers".
 */
export interface StyleModifier {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  description?: string | null;
  systemPrompt: string;
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-audit-logs".
 */
export interface AiAuditLog {
  id: number;
  tenant?: (number | null) | Tenant;
  user: number | User;
  session?: (number | null) | DraftingSession;
  requestType: 'draft' | 'refine' | 'image-generate' | 'schema-create';
  prompt?: string | null;
  model: string;
  provider: string;
  promptTokens?: number | null;
  completionTokens?: number | null;
  totalTokens?: number | null;
  estimatedCost?: number | null;
  durationMs?: number | null;
  status: 'success' | 'error' | 'timeout';
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-rate-limits".
 */
export interface AiRateLimit {
  id: number;
  userId: string;
  timestamp: string;
  requestPath: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'content-types';
        value: number | ContentType;
      } | null)
    | ({
        relationTo: 'content-items';
        value: number | ContentItem;
      } | null)
    | ({
        relationTo: 'hosted-sites';
        value: number | HostedSite;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null)
    | ({
        relationTo: 'ai-prompt-history';
        value: number | AiPromptHistory;
      } | null)
    | ({
        relationTo: 'drafting-sessions';
        value: number | DraftingSession;
      } | null)
    | ({
        relationTo: 'style-modifiers';
        value: number | StyleModifier;
      } | null)
    | ({
        relationTo: 'ai-audit-logs';
        value: number | AiAuditLog;
      } | null)
    | ({
        relationTo: 'ai-rate-limits';
        value: number | AiRateLimit;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'api-keys';
        value: number | ApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'api-keys';
        value: number | ApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  tier?: T;
  defaultLocale?: T;
  defaultLLMModel?: T;
  defaultImageModel?: T;
  domains?:
    | T
    | {
        hostname?: T;
        isPrimary?: T;
        id?: T;
      };
  branding?:
    | T
    | {
        logo?: T;
        primaryColor?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-types_select".
 */
export interface ContentTypesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  status?: T;
  originalSchema?: T;
  schema?: T;
  generatedByAI?: T;
  aiSessionId?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-items_select".
 */
export interface ContentItemsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  contentType?: T;
  fieldsData?: T;
  content?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hosted-sites_select".
 */
export interface HostedSitesSelect<T extends boolean = true> {
  name?: T;
  template?: T;
  domain?: T;
  status?: T;
  deployedUrl?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  severity?: T;
  tenant?: T;
  user?: T;
  metadata?: T;
  isImpersonated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  tenant?: T;
  label?: T;
  email?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-prompt-history_select".
 */
export interface AiPromptHistorySelect<T extends boolean = true> {
  tenant?: T;
  prompt?: T;
  generatedSchema?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drafting-sessions_select".
 */
export interface DraftingSessionsSelect<T extends boolean = true> {
  tenant?: T;
  user?: T;
  contentType?: T;
  status?: T;
  draftData?: T;
  mainMedia?: T;
  activeLocale?: T;
  selectedModel?: T;
  lastActivityAt?: T;
  versions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "style-modifiers_select".
 */
export interface StyleModifiersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  description?: T;
  systemPrompt?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-audit-logs_select".
 */
export interface AiAuditLogsSelect<T extends boolean = true> {
  tenant?: T;
  user?: T;
  session?: T;
  requestType?: T;
  prompt?: T;
  model?: T;
  provider?: T;
  promptTokens?: T;
  completionTokens?: T;
  totalTokens?: T;
  estimatedCost?: T;
  durationMs?: T;
  status?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-rate-limits_select".
 */
export interface AiRateLimitsSelect<T extends boolean = true> {
  userId?: T;
  timestamp?: T;
  requestPath?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}